version: "3.7"

services:
  backend:
    build: ./docker/
    ports:
      - 8080:8080
    volumes:
      - ./backend:/go/src/github.com/so-heee/graphql-todo-app/backend
    tty: true
    env_file: ./backend/config/.env
    command: realize start
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
