schema: '../schema/*.graphqls'
documents: 'src/graphql/queries/*.graphql'
extensions:
  codegen:
    generates:
      src/graphql/generated/graphql.ts:
        plugins:
          - typescript
          - typescript-operations
          - typescript-graphql-request
