// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"strings"
)

func TodoOrderToPaginationOrders(orders []*TodoOrder) []*Order {
	paginationOrders := make([]*Order, len(orders))

	for i, o := range orders {
		paginationOrders[i] = &Order{Field: strings.ToLower(string(*o.Field)), Direction: Direction(*o.Direction)}
	}

	return paginationOrders
}

func UserOrderToPaginationOrders(orders []*UserOrder) []*Order {
	paginationOrders := make([]*Order, len(orders))

	for i, o := range orders {
		paginationOrders[i] = &Order{Field: strings.ToLower(string(*o.Field)), Direction: Direction(*o.Direction)}
	}

	return paginationOrders
}
